// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNkIN2ROpVQ5l2RN1XOaU-lNNEK36J-0g',
    appId: '1:361180027458:web:4a7da154b0dfef3bee6bdb',
    messagingSenderId: '361180027458',
    projectId: 'events360-92269',
    authDomain: 'events360-92269.firebaseapp.com',
    storageBucket: 'events360-92269.appspot.com',
    measurementId: 'G-SZK9D112MT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATECPpyOZmtUHP_36Ovdmvo4rlY8WQQ0s',
    appId: '1:361180027458:android:ee236b82cdb73d01ee6bdb',
    messagingSenderId: '361180027458',
    projectId: 'events360-92269',
    storageBucket: 'events360-92269.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp2eE9IPKQHuAR5uE3n1DieO0yGXL-das',
    appId: '1:361180027458:ios:fc9f3c508caf9ed3ee6bdb',
    messagingSenderId: '361180027458',
    projectId: 'events360-92269',
    storageBucket: 'events360-92269.appspot.com',
    iosBundleId: 'com.example.events360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp2eE9IPKQHuAR5uE3n1DieO0yGXL-das',
    appId: '1:361180027458:ios:fc9f3c508caf9ed3ee6bdb',
    messagingSenderId: '361180027458',
    projectId: 'events360-92269',
    storageBucket: 'events360-92269.appspot.com',
    iosBundleId: 'com.example.events360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNkIN2ROpVQ5l2RN1XOaU-lNNEK36J-0g',
    appId: '1:361180027458:web:19779014d0381f17ee6bdb',
    messagingSenderId: '361180027458',
    projectId: 'events360-92269',
    authDomain: 'events360-92269.firebaseapp.com',
    storageBucket: 'events360-92269.appspot.com',
    measurementId: 'G-B0FV0KFCXP',
  );

}